# Generated by Django 5.1.5 on 2025-02-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='films/', verbose_name='загрузите фото')),
                ('title', models.CharField(max_length=100, verbose_name='укажите название фильма')),
                ('description', models.TextField(blank=True, verbose_name='укажите описание фильма')),
                ('price', models.PositiveIntegerField(default=200, verbose_name='укажите цену')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('HORROR', 'HORROR'), ('COMEDY', 'COMEDY'), ('FANTASY', 'FANTASY')], default='COMEDY', max_length=10, verbose_name='выберите жанр')),
                ('time', models.TimeField(verbose_name='укажите время просмотра')),
                ('director', models.CharField(default='Иванов Иван', max_length=100)),
                ('trailer', models.URLField(verbose_name='укажите ссылку из YOUTUBE')),
            ],
        ),
    ]
