# Generated by Django 5.1.5 on 2025-02-08 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0002_alter_filmmodel_options_filmmodel_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('review_text', models.TextField(default='Крутой фильм')),
                ('stars', models.CharField(choices=[('🌟', '🌟'), ('🌟🌟', '🌟🌟'), ('🌟🌟🌟', '🌟🌟🌟'), ('🌟🌟🌟🌟', '🌟🌟🌟🌟'), ('🌟🌟🌟🌟🌟', '🌟🌟🌟🌟🌟')], default='🌟🌟', max_length=10)),
                ('choice_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='tv_show.filmmodel')),
            ],
        ),
    ]
